const filmsAT = {
  ADD_FILM: "FILMS_ADD_FILM",
  ADD_FILMS: "FILMS_ADD_FILMS",
  FILMS_LOADING: "FILMS_LOADING",
  DELETE_FILM: "FILMS_DELETE_FILM",
  ADD_MESSAGE: "FILMS_ADD_MESSAGE",
  LOADING_FAILED: "FILMS_LOADING_FAILED",
  SET_SORTING: "FILMS_SET_SORTING",
  SET_ORDER: "FILMS_SET_ORDER",
};

export default filmsAT;
